/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AConstructorStructBody extends PStructBody
{
    private PConstructor _constructor_;
    private PStructBody _structBody_;

    public AConstructorStructBody()
    {
        // Constructor
    }

    public AConstructorStructBody(
        @SuppressWarnings("hiding") PConstructor _constructor_,
        @SuppressWarnings("hiding") PStructBody _structBody_)
    {
        // Constructor
        setConstructor(_constructor_);

        setStructBody(_structBody_);

    }

    @Override
    public Object clone()
    {
        return new AConstructorStructBody(
            cloneNode(this._constructor_),
            cloneNode(this._structBody_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConstructorStructBody(this);
    }

    public PConstructor getConstructor()
    {
        return this._constructor_;
    }

    public void setConstructor(PConstructor node)
    {
        if(this._constructor_ != null)
        {
            this._constructor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._constructor_ = node;
    }

    public PStructBody getStructBody()
    {
        return this._structBody_;
    }

    public void setStructBody(PStructBody node)
    {
        if(this._structBody_ != null)
        {
            this._structBody_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._structBody_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._constructor_)
            + toString(this._structBody_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._constructor_ == child)
        {
            this._constructor_ = null;
            return;
        }

        if(this._structBody_ == child)
        {
            this._structBody_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._constructor_ == oldChild)
        {
            setConstructor((PConstructor) newChild);
            return;
        }

        if(this._structBody_ == oldChild)
        {
            setStructBody((PStructBody) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
