/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AIfLogic extends PLogic
{
    private PTerm _if_;
    private TQuery _query_;
    private TLBrace _thenin_;
    private PImpl _then_;

    public AIfLogic()
    {
        // Constructor
    }

    public AIfLogic(
        @SuppressWarnings("hiding") PTerm _if_,
        @SuppressWarnings("hiding") TQuery _query_,
        @SuppressWarnings("hiding") TLBrace _thenin_,
        @SuppressWarnings("hiding") PImpl _then_)
    {
        // Constructor
        setIf(_if_);

        setQuery(_query_);

        setThenin(_thenin_);

        setThen(_then_);

    }

    @Override
    public Object clone()
    {
        return new AIfLogic(
            cloneNode(this._if_),
            cloneNode(this._query_),
            cloneNode(this._thenin_),
            cloneNode(this._then_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfLogic(this);
    }

    public PTerm getIf()
    {
        return this._if_;
    }

    public void setIf(PTerm node)
    {
        if(this._if_ != null)
        {
            this._if_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._if_ = node;
    }

    public TQuery getQuery()
    {
        return this._query_;
    }

    public void setQuery(TQuery node)
    {
        if(this._query_ != null)
        {
            this._query_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._query_ = node;
    }

    public TLBrace getThenin()
    {
        return this._thenin_;
    }

    public void setThenin(TLBrace node)
    {
        if(this._thenin_ != null)
        {
            this._thenin_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._thenin_ = node;
    }

    public PImpl getThen()
    {
        return this._then_;
    }

    public void setThen(PImpl node)
    {
        if(this._then_ != null)
        {
            this._then_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._then_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._if_)
            + toString(this._query_)
            + toString(this._thenin_)
            + toString(this._then_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._if_ == child)
        {
            this._if_ = null;
            return;
        }

        if(this._query_ == child)
        {
            this._query_ = null;
            return;
        }

        if(this._thenin_ == child)
        {
            this._thenin_ = null;
            return;
        }

        if(this._then_ == child)
        {
            this._then_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._if_ == oldChild)
        {
            setIf((PTerm) newChild);
            return;
        }

        if(this._query_ == oldChild)
        {
            setQuery((TQuery) newChild);
            return;
        }

        if(this._thenin_ == oldChild)
        {
            setThenin((TLBrace) newChild);
            return;
        }

        if(this._then_ == oldChild)
        {
            setThen((PImpl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
