/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AImplsImpl extends PImpl
{
    private PImpl _l_;
    private TReturn _return_;
    private PImpl _r_;

    public AImplsImpl()
    {
        // Constructor
    }

    public AImplsImpl(
        @SuppressWarnings("hiding") PImpl _l_,
        @SuppressWarnings("hiding") TReturn _return_,
        @SuppressWarnings("hiding") PImpl _r_)
    {
        // Constructor
        setL(_l_);

        setReturn(_return_);

        setR(_r_);

    }

    @Override
    public Object clone()
    {
        return new AImplsImpl(
            cloneNode(this._l_),
            cloneNode(this._return_),
            cloneNode(this._r_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAImplsImpl(this);
    }

    public PImpl getL()
    {
        return this._l_;
    }

    public void setL(PImpl node)
    {
        if(this._l_ != null)
        {
            this._l_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._l_ = node;
    }

    public TReturn getReturn()
    {
        return this._return_;
    }

    public void setReturn(TReturn node)
    {
        if(this._return_ != null)
        {
            this._return_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._return_ = node;
    }

    public PImpl getR()
    {
        return this._r_;
    }

    public void setR(PImpl node)
    {
        if(this._r_ != null)
        {
            this._r_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._r_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._l_)
            + toString(this._return_)
            + toString(this._r_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._l_ == child)
        {
            this._l_ = null;
            return;
        }

        if(this._return_ == child)
        {
            this._return_ = null;
            return;
        }

        if(this._r_ == child)
        {
            this._r_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._l_ == oldChild)
        {
            setL((PImpl) newChild);
            return;
        }

        if(this._return_ == oldChild)
        {
            setReturn((TReturn) newChild);
            return;
        }

        if(this._r_ == oldChild)
        {
            setR((PImpl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
