/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ATypeType extends PType
{
    private TLArrow _lArrow_;
    private TId _id_;
    private TRArrow _rArrow_;

    public ATypeType()
    {
        // Constructor
    }

    public ATypeType(
        @SuppressWarnings("hiding") TLArrow _lArrow_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TRArrow _rArrow_)
    {
        // Constructor
        setLArrow(_lArrow_);

        setId(_id_);

        setRArrow(_rArrow_);

    }

    @Override
    public Object clone()
    {
        return new ATypeType(
            cloneNode(this._lArrow_),
            cloneNode(this._id_),
            cloneNode(this._rArrow_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATypeType(this);
    }

    public TLArrow getLArrow()
    {
        return this._lArrow_;
    }

    public void setLArrow(TLArrow node)
    {
        if(this._lArrow_ != null)
        {
            this._lArrow_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lArrow_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TRArrow getRArrow()
    {
        return this._rArrow_;
    }

    public void setRArrow(TRArrow node)
    {
        if(this._rArrow_ != null)
        {
            this._rArrow_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rArrow_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lArrow_)
            + toString(this._id_)
            + toString(this._rArrow_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lArrow_ == child)
        {
            this._lArrow_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._rArrow_ == child)
        {
            this._rArrow_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lArrow_ == oldChild)
        {
            setLArrow((TLArrow) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._rArrow_ == oldChild)
        {
            setRArrow((TRArrow) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
