/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TBlackslash extends Token
{
    public TBlackslash()
    {
        super.setText("\\");
    }

    public TBlackslash(int line, int pos)
    {
        super.setText("\\");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TBlackslash(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBlackslash(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TBlackslash text.");
    }
}
