/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TCend extends Token
{
    public TCend()
    {
        super.setText("<nativC");
    }

    public TCend(int line, int pos)
    {
        super.setText("<nativC");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCend(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCend(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCend text.");
    }
}
