/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TCstart extends Token
{
    public TCstart()
    {
        super.setText("nativC>");
    }

    public TCstart(int line, int pos)
    {
        super.setText("nativC>");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCstart(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCstart(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCstart text.");
    }
}
