/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TTimes extends Token
{
    public TTimes()
    {
        super.setText("times");
    }

    public TTimes(int line, int pos)
    {
        super.setText("times");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTimes(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTimes(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTimes text.");
    }
}
